// <auto-generated />
namespace Shipbob.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialize_localDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialize_localDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201612051845543_Initialize_localDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
